joint_1:
  ID: 1
  Return_Delay_Time: 0
  Torque_Limit: 700
joint_2:
  ID: 2
  Return_Delay_Time: 0
  Torque_Limit: 700
joint_3:
  ID: 3
  Return_Delay_Time: 0
  Torque_Limit: 700
joint_4:
  ID: 4
  Return_Delay_Time: 0
  Torque_Limit: 700
joint_5:
  ID: 5
  Return_Delay_Time: 0
  Torque_Limit: 700